language: julia
os:
  - linux
#  - osx
julia:
  - 0.5
notifications:
  email: false
sudo: required
dist: trusty
addons:
  apt:
    sources:
    - sourceline: 'ppa:jon-severinsson/ffmpeg'
    packages:
    - ffmpeg
    - libx264-dev
env:
    global:
    - PYTHON=conda
before_script: # configure a headless display to test plot generation; http://stackoverflow.com/a/35403128
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
before_install:
  - julia -e 'Pkg.add("Conda"); using Conda; Conda.add("matplotlib")'
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("VariableHeightInvertedPendulum"); Pkg.test("VariableHeightInvertedPendulum")'
